# Site settings

email: jmgaguilera@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Bienvenid@s al blog de José Miguel González Aguilera.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jmgaguilera.github.io" # the base hostname & protocol for your site
twitter_username: jmgaguilera
github_username:  jmgaguilera
linkedin_href: jose-miguel-gonzalez-aguilera-a727b010
linkedin_username: jmgaguilera

# Build settings
markdown: kramdown

# traducciones

t:
    en:
        title: José Miguel González Aguilera
        subtitle: Looking for solutions to problems instead of problems to the solution
        home:
            entry: Articles
            subscript: Suscription
            url: index_en.html
        description: Welcome to my blog.
    es:
        title: Blog de José Miguel González Aguilera
        subtitle: Buscando soluciones a los problemas sin poner problemas a la solución
        home:
            entry: Artículos
            subscript: Suscripción
            url: index.html
        description: Bienvenid@s a mi blog.

            
